/* eslint-disable @next/next/no-css-tags */
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Navbar from "./components/Navbar";
// import '@/public/css/bootstrap.rtl.min.css'
// import '@/public/css/aos.css'
// import '@/public/css/animate.min.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coze - IT Solutions & Technology Services Bootstrap 5 Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <head>
      <link rel="icon" href="/images/favicon.png" />
        <link rel="stylesheet" href="/css/bootstrap.rtl.min.css" />
        <link rel="stylesheet" href="/css/aos.css" />
        <link rel="stylesheet" href="/css/animate.min.css" />
        <link rel="stylesheet" href="/css/meanmenu.css" />
        <link rel="stylesheet" href="/css/remixicon.css" />
        <link rel="stylesheet" href="/css/odometer.min.css" />
        <link rel="stylesheet" href="/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="/css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="/css/magnific-popup.min.css" />
        <link rel="stylesheet" href="/css/fancybox.css" />
        <link rel="stylesheet" href="/css/nice-select.min.css" />
        <link rel="stylesheet" href="/css/style.css" />
        <link rel="stylesheet" href="/css/navbar.css" />
        <link rel="stylesheet" href="/css/footer.css" />
        <link rel="stylesheet" href="/css/dark.css" />
        <link rel="stylesheet" href="/css/responsive.css" />
        <link rel="stylesheet" href="/css/rtl.css" />
      </head>
      <body className={inter.className}>
        {/* <div className="preloader">
            <div className="d-table">
                <div className="d-table-cell">
                    <div className="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
                </div>
            </div>
        </div> */}
        {/* <Navbar/> */}
        {children}
        <div className="go-top">
        <i className="ri-arrow-up-s-line" />
      </div>
        <Script data-cfasync="false" src="js/email-decode.min.js"></Script>
	      <Script src="js/jquery.min.js"></Script>
        <Script src="js/bootstrap.bundle.min.js"></Script>
        <Script src="js/jquery.meanmenu.js"></Script> 
        <Script src="js/owl.carousel.min.js"></Script>
        <Script src="js/jquery.appear.js"></Script>
        <Script src="js/odometer.min.js"></Script>
        <Script src="js/jquery.magnific-popup.min.js"></Script>
        <Script src="js/fancybox.min.js"></Script>
        <Script src="js/tweenmax.min.js"></Script>
        <Script src="js/ScrollMagic.min.js"></Script>
        <Script src="js/animation.gsap.min.js"></Script>
        <Script src="js/debug.addIndicators.min.js"></Script>
        <Script src="js/mixitup.min.js"></Script>
        <Script src="js/nice-select.min.js"></Script>
        <Script src="js/tilt.jquery.min.js"></Script>
        <Script src="js/parallax.min.js"></Script>
	      <Script src="js/jquery.ajaxchimp.min.js"></Script>
	      <Script src="js/form-validator.min.js"></Script>
        <Script src="js/contact-form-script.js"></Script>
        <Script src="js/aos.js"></Script>
        <Script src="js/wow.min.js"></Script>
        <Script src="js/main.js"></Script>
      </body>
    </html>
  );
}
