/* eslint-disable @next/next/no-css-tags */
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// import '@/public/css/bootstrap.rtl.min.css'
// import '@/public/css/aos.css'
// import '@/public/css/animate.min.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coze - IT Solutions & Technology Services Bootstrap 5 Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <head>
      <link rel="icon" href="/images/favicon.png" />
        <link rel="stylesheet" href="/css/bootstrap.rtl.min.css" />
        <link rel="stylesheet" href="/css/aos.css" />
        <link rel="stylesheet" href="/css/animate.min.css" />
        <link rel="stylesheet" href="/css/meanmenu.css" />
        <link rel="stylesheet" href="/css/remixicon.css" />
        <link rel="stylesheet" href="/css/odometer.min.css" />
        <link rel="stylesheet" href="/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="/css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="/css/magnific-popup.min.css" />
        <link rel="stylesheet" href="/css/fancybox.css" />
        <link rel="stylesheet" href="/css/nice-select.min.css" />
        <link rel="stylesheet" href="/css/style.css" />
        <link rel="stylesheet" href="/css/navbar.css" />
        <link rel="stylesheet" href="/css/footer.css" />
        <link rel="stylesheet" href="/css/dark.css" />
        <link rel="stylesheet" href="/css/responsive.css" />
        <link rel="stylesheet" href="/css/rtl.css" />
      </head>
      <body className={inter.className}>
        {children}

     

      </body>
    </html>
  );
}
